### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by danny305** [RBVI/readcif#1]
When I try to build with the 
```bash
$ meson setup builddir
```
I get the following error:
```bash
src/meson.build:16:8: ERROR: Unknown variable "shlib".
```

if I delete the shlib then its builds just fine. How important is the shlib in the meson.build directory? I am unsure of what it does. 

Thanks!

**Comment by gregcouch** [comment]
shlb is meant for building a shared library version.  It is not needed.
But it should work.  Will look into it later.

**Comment by danny305** [comment]
Yeah I spent more time reading the meson.build files. (I am not familiar with meson but with cmake) and figured that out. Thanks for the confirmation. 

FYI in the src/meson.build file. I had to switch all of the double quotes to single quotes to get meson working properly.

**Comment by gregcouch** [comment]
Thank you.  It's fixed now.
